"""
Lifecycle API endpoints — deterministic BIS standard lifecycle metadata.

Endpoint: GET /api/v1/standards/{standard_number}/lifecycle

All data is sourced from verified BIS seed lifecycle records.
No LLM inference is performed at any stage.
"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse

from app.schemas.lifecycle import StandardLifecycle
from app.services.lifecycle import LifecycleService

router = APIRouter(prefix="/standards", tags=["Standard Lifecycle"])

_lifecycle_service = LifecycleService()


@router.get(
    "/{standard_number}/lifecycle",
    response_model=StandardLifecycle,
    summary="Get verified lifecycle metadata for a BIS standard",
    description=(
        "Returns edition, status, amendment history, and related lifecycle "
        "metadata for the specified BIS standard number. "
        "All data is sourced exclusively from the verified BIS seed dataset; "
        "no information is inferred or generated by an AI model."
    ),
)
async def get_standard_lifecycle(standard_number: str) -> StandardLifecycle:
    """
    Retrieve verified lifecycle metadata for a BIS standard.

    - **standard_number**: BIS standard number, e.g. ``IS+456%3A2000`` or ``IS 1786:2008``.
      URL-encode colons and spaces as needed.
    """
    lc = _lifecycle_service.get_lifecycle(standard_number)
    if lc is None:
        raise HTTPException(
            status_code=404,
            detail=f"No lifecycle record found for standard: '{standard_number}'. "
                   "Ensure the standard number matches exactly (e.g. 'IS 456:2000').",
        )
    return lc
